server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SATELLITE-LOCATION
          uri: lb://SATELLITE-LOCATION
          predicates:
            - Path=/location/**
        - id: SATELLITE
          uri: lb://SATELLITE
          predicates:
            - Path=/satellite/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.18.0.13:8761/eureka/
  #instance:
    #hostname: localhost